server:
  port: 8761

eureka:
## Uncomment if you want to exclude eureka server from registery (so you cannot use client discovery but causes better boot speed)
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
  instance:
    instanceId: ${spring.application.name}
  server:
    waitTimeInMsWhenSyncEmpty: 0